conference_room/conference_room/urls.py
from django.contrib import admin
from django.urls import path
from conference import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainPageView.as_view(), name='main_page'),
    path('room/new', views.NewRoomView.as_view(), name='new_room'),
    path('room/modify/<int:room_id>', views.ModifyRoomView.as_view(), name='modify_room'),
    path('room/delete/<int:room_id>', views.DeleteRoomView.as_view(), name='delete_room'),
    path('room/<int:room_id>', views.ShowRoomView.as_view(), name='show_room'),
    # path('reservation', views.ReservationRoomView.as_view(), name='book_a_conference'),


]

conference_room/conference/models.py
from django.db import models
from datetime import datetime


TAKEN = (
    (True, 'Yes'),
    (False, 'No')
)


class Room(models.Model):
    name = models.CharField(max_length=32)
    number = models.IntegerField()
    description = models.CharField(max_length=128)


class Reservation(models.Model):
    date = models.DateTimeField()
    taken = models.BooleanField(choices=TAKEN)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

conference_room/conference/forms.py
from django import forms
from .models import TAKEN, Room, Reservation


class NewRoomForm(forms.Form):
    name = forms.CharField(label='Name', max_length=32)
    number = forms.IntegerField(label='Room Number')
    taken = forms.ChoiceField(choices=TAKEN, label='Taken', widget=forms.Select)
    description = forms.CharField(label='Description', widget=forms.Textarea)


class ReservationForm(forms.Form):
    date = forms.CharField(label='Date', widget=forms.SelectDateWidget)

conference_room/conference/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import Room, Reservation
from .forms import NewRoomForm, ReservationForm


class MainPageView(View):
    def get(self, request):
        rooms = Room.objects.all()
        ctx = {
            'rooms': rooms
        }
        return render(request, 'main.html', ctx)


class ShowRoomView(View):
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        return render(request, 'show.html', {'room': room})


class NewRoomView(View):
    def get(self, request):
        form = NewRoomForm()
        return render(request, 'form.html', {'form': form})

    def post(self, request):
        form = NewRoomForm(request.POST)
        if form.is_valid():
            r = Room()
            r.name = form.cleaned_data['name']
            r.number = form.cleaned_data['number']
            r.description = form.cleaned_data['description']
            r.save()
            return redirect('/')


class ModifyRoomView(View):
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        form = NewRoomForm()
        ctx = {
            'room': room,
            'form': form
        }
        return render(request, 'form.html', ctx)

    def post(self, request, room_id):
        form = NewRoomForm(request.POST)
        room = Room.objects.get(pk=room_id)
        if form.is_valid():
            r = Room()
            r.name = form.cleaned_data['name']
            r.number = form.cleaned_data['number']
            r.description = form.cleaned_data['description']
            r.pk = room.id
            r.save()
            return redirect('/')


class DeleteRoomView(View):
    def get(self, request, room_id):
        room = Room.objects.get(pk=room_id)
        room.delete()
        return redirect('/')


class ReservationRoomView(View):
    def get(self, request, room_id):
        form = ReservationForm()
        room = Room.objects.get(pk=room_id)
        ctx = {
            'form': form,
            'room': room
        }
        return render(request, 'form.html', ctx)

    def post(self, request, room_id):
        form = ReservationForm(request.POST)
        room = Room.objects.get(pk=room_id)
        if form.is_valid():
            r = Reservation()
            r.date = form.cleaned_data['date']

conference_room/conference/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Conference Room
        {% endblock %}
    </title>
</head>
<body>
    <h1>Conference Room</h1>
    {% block content %}

    {% endblock %}


    {% block footer %}
        Copyright by Wojtek
    {% endblock %}
</body>
</html>

conference_room/conference/templates/form.html
{% extends 'base.html' %}

{% block title %}
Form
{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p}}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

conference_room/conference/templates/main.html
{% extends 'base.html' %}

{% block title %}
    Main Page View
{% endblock %}

{% block content %}
    <ul>
        {% for room in rooms %}
        <li>
            <p>{{ room.number }}. {{ room.name }}</p>
            <a href="room/{{ room.id }}"><button>Show Details</button></a>
        </li>
        {% endfor %}
    </ul>

<p><a href="room/new"><button>Add New Room</button></a></p>
<p><a href="reservation"><button>Book a Conference</button></a></p>
{% endblock %}

conference_room/conference/templates/show.html
{% extends 'base.html' %}

{% block title %}
Show Room View
{% endblock %}

{% block content %}

<h2>Room Details</h2>

<ul>
    {% if rooms.id == room_id %}
        <li>
            <p>Room: {{ room.number }}. {{room.name }}</p>
            <p>Description: {{ room.description }}</p>
            <p>Taken: {{ room.get_taken_display }}</p>
            <p><a href="modify/{{ room.id }}"><button>Modify</button></a></p>
            <p><a href="delete/{{ room.id }}"><button>Delete</button></a></p>
        </li>
    {% endif %}
</ul>
{% endblock %}